# # -*- coding: utf-8 -*-
# """Conversion.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1LHshF23bNCV3jeM4LV9iaJHSVxgx-uCo
# """

# # import required modules
# import subprocess

# # convert mp3 to wav file
# subprocess.call(['ffmpeg', '-i', 'ThunderClap4HvyC SDT2042602.mp3',
#                  'converted_to_wav_file.wav'])


# from os import path
# from pydub import AudioSegment

# # assign files
# input_file = "C:\\Users\\gupta\\Downloads\\gun.mp3"
# output_file = "result.wav"

# # convert mp3 file to wav file
# sound = AudioSegment.from_mp3(input_file)
# sound.export(output_file, format="wav")

from pydub import AudioSegment
from pydub.playback import play

# assign files
input_file = "C:\\Users\\gupta\\Downloads\\gun.mp3"
output_file = "result.wav"

# convert mp3 file to wav file using pydub
sound = AudioSegment.from_mp3(input_file)
sound.export(output_file, format="wav")

# play the converted WAV file (optional)
play(sound)
